name: amazon-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.1
  - numpy=1.24.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.17.0
  - scikit-learn=1.3.0
  - sqlalchemy=2.0.21
  - scipy=1.11.3
  - streamlit=1.28.1
  - pip
  - pip:
    - streamlit-aggrid
    - streamlit-plotly-events
