name: amazon-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - streamlit>=1.28.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.17.0
  - scikit-learn>=1.3.0
  - sqlalchemy>=2.0.0
  - scipy>=1.11.0
  - pip
  - pip:
    - streamlit-aggrid
    - streamlit-plotly-events
