# Database Configuration
[database]
host = "localhost"
port = 5432
database = "amazon_analytics"
username = "analytics_user"
password = "your_secure_password"

# API Keys (if needed)
[api_keys]
google_analytics = "your_ga_key"
external_data_source = "your_api_key"

# Email Configuration
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
email = "analytics@company.com"
password = "your_email_password"
